[package]
name = "bfs"
version = "0.1.0"
edition = "2021"
description = """
SeBS BFS
"""

[lib]
name = "bfs"
crate-type = ["rlib", "cdylib"]

[dependencies]
rand = "0.8"
petgraph = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proxy-guest = { path = "../../shared/proxy-guest" }
