---
- name: Run Mosaic Benchmarks
  hosts: all
  become: yes # Run as root for installations.
  strategy: free
  vars:
    repo_url: "github.com/cloudsys-dpss-inescid/mosaic.git"
    repo_dir: "/home/ubuntu/mosaic"

  tasks:
    - name: Update apt and install dependencies
      apt:
        name: ['git', 'docker.io', 'curl', 'unzip', 'awscli']
        state: present
        update_cache: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # Reset connection so the docker group change takes effect for the ubuntu user.
    - name: Reset ssh connection to allow user changes to affect docker
      meta: reset_connection

- name: Setup user space and run benchmarks
  hosts: all
  become: no # Run as the normal 'ubuntu' user from here on.
  strategy: free
  vars:
    repo_dir: "/home/ubuntu/mosaic"
    s3_bucket: "{{ s3_bucket }}"
    target_benchmarks: "{{ target_benchmarks }}"

  tasks:
    - name: Clone private repository
      git:
        repo: "https://{{ repo_url }}"
        dest: "{{ repo_dir }}"
        force: yes

    - name: Start Docker webserver
      shell: "./start-webserver.sh"
      args:
        chdir: "{{ repo_dir }}/core-modules/scripts/data"

    - name: Run benchmarking script
      shell: "bash benchmark-throughput-aws.sh '{{ configs }}' '{{ s3_bucket }}' '{{ inventory_hostname }}' '{{ target_benchmarks }}'"
      args:
        chdir: "{{ repo_dir }}/core-modules/scripts"
        executable: /bin/bash
      environment:
        ITERATIONS: "10"
        BENCHMARK_DURATION: "60"
        WARMUP_ITERATIONS: "10"

    - name: Find all JSON result files
      find:
        paths: "{{ repo_dir }}/core-modules/plots/mosaic-throughput"
        patterns: "*.json"
      register: json_files

    - name: Fetch JSON results back to local machine
      fetch:
        src: "{{ item.path }}"
        dest: "./results/{{ inventory_hostname }}/"
        flat: yes
      loop: "{{ json_files.files }}"
