package docs:adder@0.1.0;

interface add {
    add: func(x: u32, y: u32) -> u32;
}

interface hosted {
    record point {
        x: u32,
        y: u32,
    }

    host-function: func(x: u32) -> u32;
    host-function-print: func(x: string);
    host-function-get-point: func(x: u32, y: u32) -> point;
    host-function-print-point: func(p: point);
}

world adder {
    import hosted;
    export add;
}
