[package]
name = "pagerank"
version = "0.1.0"
edition = "2021"
description = """
Example Rust-based WebAssembly host that executes WebAssembly components
"""

[dependencies]
runner = { path = "../../../runner" }
anyhow = "1.0"
wasmtime = "34.0"
pagerank-lib = { path = "../../../shared/pagerank-lib" }
